logging:
  path: ./logs

server:
  port: ${PORT:5003}

spring:
  cloud:
    consul:
      discovery:
        tags: traefik.frontend.rule=PathPrefixStrip:/auth

jalgoarena.security.jwt:
  tokenExpirationTime: 43200 # Minutes
  tokenIssuer: jalgoarena.com
  tokenSigningKey: U9FdVDcRlKRV+WDzSOCmdeKkhR9MWANj1Ksti9GiXPdzgyL4LBGhFLvzDxOkJDg/JvD65s3rbcUda757Re4uAA==
